### ISSUE TITLE
Allow pending external accounts to "recover" their password

### ISSUE THREAD

**Issue by fishilico** [Polytechnique-org/xorgauth#107]
Some group websites (eg. https://x-nucleaire.polytechnique.org/ ) rely on the SSO to authenticate their users. When the group has members who are not alumni, these members have "external accounts" in the database, and they can use the authentication system.

Currently activated external accounts work fine (ie. external accounts who already have a password), but pending accounts are not transmitted between Plat/al and auth.polytechnique.org , cf. https://github.com/Polytechnique-org/xorgauth/blob/582b0ed1a35b019d17cc1ea8ba3477c3cb339b66/scripts/export_platal_to_json.py#L65

    sql = """
        SELECT  a.uid, a.hruid, a.password, a.type, a.is_admin,
                a.firstname, a.lastname, a.full_name, a.directory_name, a.display_name,
                a.sex, a.email,
                p.ax_id, p.xorg_id, pd.promo, pe.grad_year
          FROM  accounts AS a
     LEFT JOIN  account_profiles AS ap ON (ap.uid = a.uid AND FIND_IN_SET('owner', ap.perms))
     LEFT JOIN  profiles AS p ON (p.pid = ap.pid)
     LEFT JOIN  profile_display AS pd ON (pd.pid = p.pid)
     LEFT JOIN  profile_education AS pe ON (pe.pid = p.pid AND FIND_IN_SET(\'primary\', pe.flags))
         WHERE  a.state = 'active'
      GROUP BY  a.uid
    """

Could we change the ``WHERE`` clause to ``WHERE  a.state IN ('active', 'pending')``? Would such a change have nasty side effects?

For reference, the issue has been reported by a user, https://support.polytechnique.org/otrs/index.pl?Action=AgentTicketZoom;TicketID=125092 .

**Comment by vberger** [comment]
I think this should be good, as we already handle passwordless accounts:

https://github.com/Polytechnique-org/xorgauth/blob/582b0ed1a35b019d17cc1ea8ba3477c3cb339b66/xorgauth/management/commands/importaccounts.py#L115-L120
