### ISSUE TITLE
Add a test for the password change form

### ISSUE THREAD

**Issue by fishilico** [Polytechnique-org/xorgauth#79]
The password change form has been broken since https://github.com/Polytechnique-org/xorgauth/commit/ec35e81065752485c85e013d3a1959545e7e3577 , fixed in https://github.com/Polytechnique-org/xorgauth/pull/78 because the password change form calls a ``validate`` method on password validators and this method was missing. We should have a test in order to prevent this issue from happening again.

**Comment by tizot** [comment]
I don't really get how we can _test_ this. If we are to provide new password validators, shouldn't we rather add an abstract class `BasePasswordValidator` that each new validator would inherit from, ensuring then that the validator exposes the correct API?
