### ISSUE TITLE
Allow login with 2-digit study year

### ISSUE THREAD

**Issue by fishilico** [Polytechnique-org/xorgauth#88]
Many people are writing to the support because they fail to log in with "firstname.lastname.65", because  their study year is 1965. Of course "firstname.lastname.1965" works, but they seem to like "firstname.lastname.65". We should support the 2-digit study year at least for the 19XX years.

**Comment by GuillaumeDIDIER** [comment]
The question is how do we deal with collisions ? The logic would be let's look for all user matching first name.lastname.XX65 and if there's more than one complain with please use your full 4 digit promotion ?

**Comment by vberger** [comment]
@GuillaumeDIDIER we already allow login with just `prenom.nom`, and silently fail login if there is a collision. See

https://github.com/Polytechnique-org/xorgauth/blob/master/xorgauth/accounts/models.py#L65

A first step would be to just do the same thing. And a second-step refinement would be to add a message asking for a non-ambiguous login, both for `prenom.nom` and `prenom.nom.XX`

**Comment by tizot** [comment]
I can have a look at that issue :-)

**Comment by fishilico** [comment]
Implemented in https://github.com/Polytechnique-org/xorgauth/pull/95
